apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: project
  name: reminder
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: reminder
              image: appropriate/curl:latest
              command:
                - "/bin/sh"
                - "-c"
                - |
                  URL=$(curl -s -I https://en.wikipedia.org/wiki/Special:Random | grep -i Location | awk '{print $2}' | tr -d '\r')
                  curl -X POST http://todo-backend-svc:2348/todos \
                  -H 'Content-Type: application/json' \
                  -d "{\"text\": \"Read $URL\"}"
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
