apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: todo-backend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: jovankarmakka/todo-backend:v0.2
          imagePullPolicy: Always
          env:
            - name: POSTGRES_USER
              value: "jovan"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgress-password
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: "project"