apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: pingpong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      volumes:
        - name: pingpong-image
          persistentVolumeClaim:
            claimName: pingpong-claim
      containers:
        - name: pingpong
          image: jovankarmakka/pingpong:v0.8
          imagePullPolicy: Always
          volumeMounts:
          - name: pingpong-image
            mountPath: /usr/src/app/files
