apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: part1-ingress
spec:
  rules:
  - http:
      paths:
      - path: /logoutput
        pathType: Prefix
        backend:
          service:
            name: logoutput-svc
            port:
              number: 2345       
      - path: /pingpong
        pathType: Prefix
        backend:
          service:
            name: pingpong-svc
            port:
              number: 2346
      - path: /project
        pathType: Prefix
        backend:
          service:
            name: project-svc
            port:
              number: 2347
           