apiVersion: apps/v1
kind: Deployment
metadata:
  name: logoutput-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      volumes:
        - name: pingpong-image
          persistentVolumeClaim:
            claimName: pingpong-claim
      containers:
        - name: logoutput
          image: jovankarmakka/log:v0.2
          imagePullPolicy: Always
          volumeMounts:
          - name: pingpong-image
            mountPath: /usr/src/app/files
